=== heiglandreas/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://heigl.org/holidays"
           xmlns="https://heigl.org/holidays"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynamelist">
        <xs:list itemType="daynames" />
    </xs:simpleType>
    <xs:simpleType name="calendars">
        <xs:restriction base="xs:string">
            <xs:enumeration value="buddhist"/>
            <xs:enumeration value="chinese"/>
            <xs:enumeration value="coptic"/>
            <xs:enumeration value="ethiopian"/>
            <xs:enumeration value="gregorian"/>
            <xs:enumeration value="hebrew"/>
            <xs:enumeration value="indian"/>
            <xs:enumeration value="islamic"/>
            <xs:enumeration value="islamic-civil"/>
            <xs:enumeration value="islamic-umalqura"/>
            <xs:enumeration value="islamic-rgsa"/>
            <xs:enumeration value="islamic-tbla"/>
            <xs:enumeration value="japanese"/>
            <xs:enumeration value="persian"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="replaced" type="daynamelist" use="optional" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
        <xs:attribute name="previous" type="daynames" use="optional"/>
        <xs:attribute name="previouswhen" type="daynamelist" use="optional"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="resourceAttributes">
        <xs:attribute name="href" type="xs:anyURI" use="required"/>
        <xs:attribute name="lastChecked" type="xs:date" use="required" />
    </xs:attributeGroup>
    <xs:attributeGroup name="forward">
        <xs:attribute name="forwardto" type="daynames" use="optional"/>
        <xs:attribute name="forwardwhen" type="daynamelist" use="optional" />
    </xs:attributeGroup>
    <xs:attributeGroup name="rewind">
        <xs:attribute name="rewindto" type="daynames" use="optional"/>
        <xs:attribute name="rewindwhen" type="daynamelist" use="optional" />
    </xs:attributeGroup>
    <xs:element name="resources">

    </xs:element>
    <xs:element name="holidays">
        <!--
        All elements have to be within the root element "holidays".

        Within this root element we expect a list of entries of type
        "easter", "easterorthodox", "date", "dateFollowUp" or "relative"

        Explanations follow on the respective elements
        -->
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="resources" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attributeGroup ref="resourceAttributes"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easter" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are relative to the Easter date as calculated for the
                    Western christian churches. The actual day is referenced by an
                    offset from easter-sunday. Days before easter sunday have a
                    negative offset, days after have a positive offset
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easterorthodox" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are relative to the Easter date as calculated for the
                    Eastern Christian churches. The actual day is referenced by an
                    offset from easter-sunday. Days before easter sunday have a
                    negative offset, days after have a positive offset
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="date" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are defined by their actual date like the 4th of July
                    or 25th of December.

                    The actual day is referenced by at least a day and a month attribute.
                    For special occasions where a day is only a holiday in a certain year
                    it can also have a year attribute. Note that you will need multiple
                    entries for multiple years.
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateAttributes"/>
                                <xs:attributeGroup ref="rewind"/>
                                <xs:attributeGroup ref="forward"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dateFollowUp" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateFollowUpAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relative" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    This is similar to the dateFollowUp but the relation can be
                    more complext.

                    Again the date the relation is referenced from is given via
                    day and month attributes but the relation itself is given in
                    the relation attribute and can be anything that
                    http://php.net/manual/de/datetimeimmutable.modify.php
                    can handle. Like "last sunday -3 weeks" from 25th of december
                    would be the 1st sunday in advent
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="relativeAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== heiglandreas/holidayChecker/share/MD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Moldova" lastChecked="2026-07-26">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true">New Year's Day</date>
	<date day="7" month="1" free="true">Orthodox Christmas</date>
	<date day="8" month="1" free="true">Orthodox Christmas</date>
	<date day="8" month="3" free="true">International Women's Day</date>
	<easterorthodox offset="0" free="true">Orthodox Easter</easterorthodox>
	<easterorthodox offset="9" free="true">Easter of Blajini</easterorthodox>
	<date day="1" month="5" free="true">Labour Day</date>
	<date day="9" month="5" free="true">Europe Day</date>
	<date day="1" month="6" free="true">Children's Day</date>
	<date day="27" month="8" free="true">Independence Day</date>
	<date day="31" month="8" free="true">National Language Day</date>
	<date day="25" month="12" free="true">Christmas Day</date>
</holidays>

=== heiglandreas/holidayChecker/share/LI.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://www.gesetze.li/konso/1967006000" lastChecked="2026-10-15">Arbeitsgesetz, Art. 18</resource>
		<resource href="https://tourismus.li/en/our-country/about-liechtenstein/bank-holidays-in-liechtenstein/" lastChecked="2026-10-15">Liechtenstein Marketing</resource>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Liechtenstein" lastChecked="2026-10-15">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true">Neujahr</date>
	<date day="2" month="1" free="false">Berchtoldstag</date>
	<date day="6" month="1" free="true">Heilige Drei Könige</date>
	<date day="2" month="2" free="true">Mariä Lichtmess</date>
	<easter offset="-47" free="false">Fasnachtsdienstag</easter>
	<date day="19" month="3" free="true">Josefstag</date>
	<easter offset="-2" free="false">Karfreitag</easter>
	<easter offset="0" free="true">Ostersonntag</easter>
	<easter offset="1" free="true">Ostermontag</easter>
	<date day="1" month="5" free="true">Tag der Arbeit</date>
	<easter offset="39" free="true">Auffahrt</easter>
	<easter offset="49" free="true">Pfingstsonntag</easter>
	<easter offset="50" free="true">Pfingstmontag</easter>
	<easter offset="60" free="true">Fronleichnam</easter>
	<date day="15" month="8" free="true">Staatsfeiertag</date>
	<date day="8" month="9" free="true">Mariä Geburt</date>
	<date day="1" month="11" free="true">Allerheiligen</date>
	<date day="8" month="12" free="true">Mariä Empfängnis</date>
	<date day="24" month="12" free="false">Heiligabend</date>
	<date day="25" month="12" free="true">Weihnachten</date>
	<date day="26" month="12" free="true">Stephanstag</date>
	<date day="31" month="12" free="false">Silvester</date>
</holidays>

=== heiglandreas/holidayChecker/share/RS-Latn.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Serbia" lastChecked="2026-07-26">Wikipedia</resource>
	</resources>
	<dateFollowUp day="1" month="1" followup="monday" replaced="sunday"  free="true" comment="New Years Day">Nova godina</dateFollowUp>
	<dateFollowUp day="2" month="1" followup="monday" replaced="sunday" free="true" comment="New Years Day">Nova godina</dateFollowUp>
	<date day="7" month="1" free="true" comment="Christmas Day">Božić</date>
	<dateFollowUp followup="monday" replaced="sunday" day="15" month="2" free="true" comment="Statehood Day">Dan državnosti</dateFollowUp>
	<dateFollowUp followup="monday" replaced="sunday" day="16" month="2" free="true" comment="Statehood Day">Dan državnosti</dateFollowUp>
	<easterorthodox offset="-2" free="true" comment="Good Friday">Veliki petak</easterorthodox>
	<easterorthodox offset="1" free="true" comment="Easter Monday">Vaskrsni ponedeljak </easterorthodox>
	<dateFollowUp day="1" month="5" followup="monday" free="true" replaced="sunday" comment="Labour Day">Praznik rada</dateFollowUp>
	<dateFollowUp day="2" month="5" followup="monday" free="true" replaced="sunday" comment="Labour Day">Praznik rada</dateFollowUp>
	<dateFollowUp day="11" month="11" followup="monday" free="true" replaced="sunday" comment="Armistice Day">Dan primirja</dateFollowUp>
	<date day="27" month="1" free="false" comment="Saint Sava Day">Savindan</date>
	<date day="22" month="4" free="false" comment="Holocaust, Genocide and other Fascist Crimes Victims of the World War II Remembrance Day">Dan sećanja na žrtve holokausta, genocida i drugih žrtava fašizma u Drugom svetskom ratu</date>
	<date day="9" month="5" free="false" comment="Victory Day">Dan pobede</date>
	<date day="28" month="6" free="false" comment="Vidovdan">Vidovdan</date>
	<date day="15" month="9" free="false" comment="Day of Serb Unity, Freedom, and the National Flag">Dan srpskog jedinstva, slobode i nacionalne zastave</date>
	<date day="21" month="10" free="false" comment="World War II Serbian Victims Remembrance Day">Dan sećanja na srpske žrtve u Drugom svetskom ratu</date>
</holidays>

=== heiglandreas/holidayChecker/share/PY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Paraguay" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true" comment="New Year">Ano Nuevo</date>
	<date day="1" month="3" free="true" comment="National Heroes Day">Dia de los héroes</date>
	<easter offset="-4" free="true" comment="Maundy Thursday">Jueves Santo</easter>
	<easter offset="-3" free="true" comment="Good Friday">Viernes Santo</easter>
	<date day="1" month="5" free="true" comment="Labour Day">Día de los Trabajadores</date>
	<date day="14" month="5" free="true" comment="Independence Day">Dia de la Independencia</date>
	<date day="12" month="6" free="true" comment="Chaco Armistice Day">Dia de la Paz del Chaco</date>
	<date day="15" month="8" free="true" comment="Foundation of Asunción">Fundación de Asunción</date>
	<date day="29" month="9" free="true" comment="Battle of Boqueron">Victoria de Boquerón</date>
	<date day="8" month="12" free="true" comment="Virgin of Caacupe">Virgen de Caacupé</date>
	<date day="25" month="12" free="true"	comment="Christmas Day">Día de Navidad</date>
</holidays>

=== heiglandreas/holidayChecker/share/GY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Guyana" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true">New Year's Day</date>
	<date day="23" month="2" free="true">Republic Day</date>
	<date day="15" month="12" free="true" calendar="indian">Phagwah</date>
	<easter offset="-2" free="true">Good Friday</easter>
	<easter offset="1" free="true">Easter Monday</easter>
	<date day="1" month="5" free="true">Labour</date>
	<date day="5" month="5" free="true">Arrival Day</date>
	<date day="26" month="5" free="true">Independence Day</date>
	<relative day="30" month="6" relation="next Monday" free="true">CARICOM Day</relative>
	<date day="1" month="8" free="true">Emancipation Day</date>
	<date day="27" month="7" free="true" calendar="indian">Diwali</date>
	<date day="25" month="12" free="true">Christmas Day</date>
	<date day="26" month="12" free="true">Boxing Day</date>
	<date day="12" month="3" free="true" calendar="islamic-civil">Youman-Nabi</date>
	<date day="15" month="3" free="true" calendar="islamic-civil">Youman-Nabi</date>
	<date day="10" month="12" free="true" calendar="islamic-civil">Eid-ul-Adha</date>
</holidays>

=== heiglandreas/holidayChecker/share/CL.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
    <resources>
        <resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Chile" lastChecked="2022-10-27">Wikipedia</resource>
    </resources>
    <date day="1" month="1" free="true" comment="New Year's Day">Año Nuevo</date>
		<easter offset="-2" free="true" comment="Good Friday">Viernes Santo</easter>
		<easter offset="-1" free="true" comment="Holy Saturday">Sábado Santo</easter>
    <date day="1" month="5" free="true" comment="Labour Day">Día del Trabajo</date>
    <date day="21" month="5" free="true" comment="Navy Day">Día de las Glorias Navales</date>
    <date day="7" month="6" free="true" comment="Battle of Arica">Asalto y Toma del Morro de Arica</date>
    <date day="21" month="6" free="true" comment="National Day of Aboriginal Peoples">Día Nacional de los Pueblos Indígenas</date>
    <date day="27" month="6" forwardto="monday" forwardwhen="tuesday wednesday thursday" rewindto="monday" rewindwhen="friday" free="true" comment="Saint Peter and Saint Paul">San Pedro y San Pablo</date>
    <date day="16" month="7" forwardto="monday" forwardwhen="tuesday wednesday thursday" rewindto="monday" rewindwhen="friday" free="true" comment="Our Lady of Mount Carmel">Virgen del Carmen</date>
    <date day="15" month="8" free="true" comment="Assumption of Mary">Asunción de la Virgen</date>
    <date day="20" month="8" free="true" comment="Nativity of Liberator Bernardo O'Higgins">Nacimiento del Prócer de la Independencia</date>
    <date day="4" month="9" free="true" comment="National plebiscite">Plebiscito nacional</date>
    <date day="18" month="9" free="true" comment="National Day">Fiestas Patrias</date>
    <date day="19" month="9" free="true" comment="Army Day">Día de las Glorias del Ejército</date>
    <date day="12" month="10" forwardto="monday" forwardwhen="tuesday wednesday thursday" rewindto="monday" rewindwhen="friday" free="true" comment="Columbus Day">Día de las Glorias del Ejército</date>
    <date day="31" month="10" free="true" comment="Reformation Day">Día Nacional de las Iglesias Evangélicas y Protestantes</date>
    <date day="1" month="11" free="true" comment="All Saints">Día de Todos los Santos</date>
    <date day="8" month="12" free="true" comment="Immaculate Conception">Inmaculada Concepción</date>
    <date day="25" month="12" free="true" comment="Christmas Day">Navidad / Natividad del Señor</date>
</holidays>

=== heiglandreas/holidayChecker/share/UA-Latn.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Ukraine" lastChecked="2026-07-26">Wikipedia - Note that during the war public holidays are working days!</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year">Novyi Rik</date>
	<date day="8" month="3" free="true" comment="International Wommens Day">Mizhnarodnyi zhinochyi den</date>
	<easterorthodox offset="0" free="true" comment="Easter" lastobservance="2023">Velykden</easterorthodox>
	<easter offset="0" free="true" comment="Easter" firstobservance="2024">Velykden</easter>
	<easterorthodox offset="49" free="true" comment="Pentecost" lastobservance="2023">Triitsia</easterorthodox>
	<easter offset="49" free="true" comment="Pentecost" firstobservance="2024">Triitsia</easter>
	<date day="1" month="5" free="true" comment="International Workers Day">Den pratsi</date>
	<date day="2" month="5" free="true" comment="International Workers Day" lastobservance="2018">Den pratsi</date>
	<date day="8" month="5" free="true" comment="Day of Remembrance and Victory over Nazism in World War II, 1939–1945">Den pamiati ta peremohy nad natsyzmom u Druhii svitovii viini 1939–1945 rokiv</date>
	<date day="28" month="6" free="true" comment="Constitution Day">Den Konstytutsii Ukrainy</date>
	<date day="15" month="7" free="true" comment="Statehood Day" firstobservance="2024">Den Ukrainskoi Derzhavnosti</date>
	<date day="28" month="7" free="true" comment="Statehood Day" lastobservance="2023">Den Ukrainskoi Derzhavnosti</date>
	<date day="24" month="8" free="true" comment="Independence Day">Den Nezalezhnosti Ukrainy</date>
	<date day="1" month="10" free="true" comment="Defenders of Ukraine Day" firstobservance="2023">Den zakhysnykiv i zakhysnyts Ukrainy</date>
	<date day="14" month="10" free="true" comment="Defenders of Ukraine Day" firstobservance="2015" lastobservance="2022">Den zakhysnykiv i zakhysnyts Ukrainy</date>
	<date day="25" month="12" free="true" comment="Christmas" firstobservance="2017">Rizdvo Khrystove</date>
	<date day="7" month="1" free="true" comment="Christmas (Gregorian Calendar)" lastobservance="2022">Rizdvo Khrystove</date>
</holidays>

=== heiglandreas/holidayChecker/share/RS-Cyrl.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Serbia" lastChecked="2026-07-26">Wikipedia</resource>
	</resources>
	<dateFollowUp day="1" month="1" followup="monday" replaced="sunday"  free="true" comment="New Years Day">Нова година</dateFollowUp>
	<dateFollowUp day="2" month="1" followup="monday" replaced="sunday" free="true" comment="New Years Day">Нова година</dateFollowUp>
	<date day="7" month="1" free="true" comment="Christmas Day">Божић</date>
	<dateFollowUp followup="monday" replaced="sunday" day="15" month="2" free="true" comment="Statehood Day">Дан државности</dateFollowUp>
	<dateFollowUp followup="monday" replaced="sunday" day="16" month="2" free="true" comment="Statehood Day">Дан државности</dateFollowUp>
	<easterorthodox offset="-2" free="true" comment="Good Friday">Велики петак</easterorthodox>
	<easterorthodox offset="1" free="true" comment="Easter Monday">Васкрсни понедељак</easterorthodox>
	<dateFollowUp day="1" month="5" followup="monday" free="true" replaced="sunday" comment="Labour Day">Празник рада</dateFollowUp>
	<dateFollowUp day="2" month="5" followup="monday" free="true" replaced="sunday" comment="Labour Day">Празник рада</dateFollowUp>
	<dateFollowUp day="11" month="11" followup="monday" free="true" replaced="sunday" comment="Armistice Day">Дан примирја</dateFollowUp>
	<date day="27" month="1" free="false" comment="Saint Sava Day">Савиндан</date>
	<date day="22" month="4" free="false" comment="Holocaust, Genocide and other Fascist Crimes Victims of the World War II Remembrance Day">Дан сећања на жртве холокауста, геноцида и других жртава фашизма у Другом светском рату</date>
	<date day="9" month="5" free="false" comment="Victory Day">Дан победе</date>
	<date day="28" month="6" free="false" comment="Vidovdan">Видовдан</date>
	<date day="15" month="9" free="false" comment="Day of Serb Unity, Freedom, and the National Flag">Дан српског јединства, слободе и националне заставе</date>
	<date day="21" month="10" free="false" comment="World War II Serbian Victims Remembrance Day">Дан сећања на српске жртве у Другом светском рату</date>
</holidays>
