=== heiglandreas/holidayChecker/share/holidays.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://heigl.org/holidays"
           xmlns="https://heigl.org/holidays"
           elementFormDefault="qualified">
    <xs:simpleType name="monthInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayInt">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynames">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sunday"/>
            <xs:enumeration value="monday"/>
            <xs:enumeration value="tuesday"/>
            <xs:enumeration value="wednesday"/>
            <xs:enumeration value="thursday"/>
            <xs:enumeration value="friday"/>
            <xs:enumeration value="saturday"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="daynamelist">
        <xs:list itemType="daynames" />
    </xs:simpleType>
    <xs:simpleType name="calendars">
        <xs:restriction base="xs:string">
            <xs:enumeration value="buddhist"/>
            <xs:enumeration value="chinese"/>
            <xs:enumeration value="coptic"/>
            <xs:enumeration value="ethiopian"/>
            <xs:enumeration value="gregorian"/>
            <xs:enumeration value="hebrew"/>
            <xs:enumeration value="indian"/>
            <xs:enumeration value="islamic"/>
            <xs:enumeration value="islamic-civil"/>
            <xs:enumeration value="islamic-umalqura"/>
            <xs:enumeration value="islamic-rgsa"/>
            <xs:enumeration value="islamic-tbla"/>
            <xs:enumeration value="japanese"/>
            <xs:enumeration value="persian"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:attributeGroup name="easterAttributes">
        <xs:attribute name="offset" type="xs:integer" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="year" type="xs:integer" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="dateFollowUpAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="followup" type="daynames" use="required" />
        <xs:attribute name="replaced" type="daynamelist" use="optional" />
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
        <xs:attribute name="calendar" type="calendars"/>
        <xs:attribute name="previous" type="daynames" use="optional"/>
        <xs:attribute name="previouswhen" type="daynamelist" use="optional"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="relativeAttributes">
        <xs:attribute name="day" type="dayInt" use="required"/>
        <xs:attribute name="month" type="monthInt" use="required"/>
        <xs:attribute name="relation" type="xs:string" use="required"/>
        <xs:attribute name="free" type="xs:boolean" use="required"/>
        <xs:attribute name="comment" type="xs:string"/>
    </xs:attributeGroup>
    <xs:attributeGroup name="resourceAttributes">
        <xs:attribute name="href" type="xs:anyURI" use="required"/>
        <xs:attribute name="lastChecked" type="xs:date" use="required" />
    </xs:attributeGroup>
    <xs:attributeGroup name="forward">
        <xs:attribute name="forwardto" type="daynames" use="optional"/>
        <xs:attribute name="forwardwhen" type="daynamelist" use="optional" />
    </xs:attributeGroup>
    <xs:attributeGroup name="rewind">
        <xs:attribute name="rewindto" type="daynames" use="optional"/>
        <xs:attribute name="rewindwhen" type="daynamelist" use="optional" />
    </xs:attributeGroup>
    <xs:element name="resources">

    </xs:element>
    <xs:element name="holidays">
        <!--
        All elements have to be within the root element "holidays".

        Within this root element we expect a list of entries of type
        "easter", "easterorthodox", "date", "dateFollowUp" or "relative"

        Explanations follow on the respective elements
        -->
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="resources" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attributeGroup ref="resourceAttributes"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easter" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are relative to the Easter date as calculated for the
                    Western christian churches. The actual day is referenced by an
                    offset from easter-sunday. Days before easter sunday have a
                    negative offset, days after have a positive offset
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="easterorthodox" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are relative to the Easter date as calculated for the
                    Eastern Christian churches. The actual day is referenced by an
                    offset from easter-sunday. Days before easter sunday have a
                    negative offset, days after have a positive offset
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="easterAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="date" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    Days that are defined by their actual date like the 4th of July
                    or 25th of December.

                    The actual day is referenced by at least a day and a month attribute.
                    For special occasions where a day is only a holiday in a certain year
                    it can also have a year attribute. Note that you will need multiple
                    entries for multiple years.
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateAttributes"/>
                                <xs:attributeGroup ref="rewind"/>
                                <xs:attributeGroup ref="forward"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dateFollowUp" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="dateFollowUpAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="relative" minOccurs="0" maxOccurs="unbounded">
                    <!--
                    This is similar to the dateFollowUp but the relation can be
                    more complext.

                    Again the date the relation is referenced from is given via
                    day and month attributes but the relation itself is given in
                    the relation attribute and can be anything that
                    http://php.net/manual/de/datetimeimmutable.modify.php
                    can handle. Like "last sunday -3 weeks" from 25th of december
                    would be the 1st sunday in advent
                    -->
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attributeGroup ref="relativeAttributes"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== heiglandreas/holidayChecker/share/UA-Cyrl.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Ukraine" lastChecked="2026-07-26">Wikipedia - Note that during the war public holidays are working days!</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New Year">Новий рік</date>
	<date day="8" month="3" free="true" comment="International Wommens Day">Міжнародний жіночий день</date>
	<easterorthodox offset="0" free="true" comment="Easter" lastobservance="2023">Великдень</easterorthodox>
	<easter offset="0" free="true" comment="Easter" firstobservance="2024">Великдень</easter>
	<easterorthodox offset="49" free="true" comment="Pentecost" lastobservance="2023">Трійця</easterorthodox>
	<easter offset="49" free="true" comment="Pentecost" firstobservance="2024">Трійця</easter>
	<date day="1" month="5" free="true" comment="International Workers Day">День праці</date>
	<date day="2" month="5" free="true" comment="International Workers Day" lastobservance="2018">День праці</date>
	<date day="8" month="5" free="true" comment="Day of Remembrance and Victory over Nazism in World War II, 1939–1945">День пам'яті та перемоги над нацизмом у Другій світовій війні 1939–1945 років</date>
	<date day="28" month="6" free="true" comment="Constitution Day">День Конституції України</date>
	<date day="15" month="7" free="true" comment="Statehood Day" firstobservance="2024">День Української Державності </date>
	<date day="28" month="7" free="true" comment="Statehood Day" lastobservance="2023">День Української Державності </date>
	<date day="24" month="8" free="true" comment="Independence Day">День Незалежності України</date>
	<date day="1" month="10" free="true" comment="Defenders of Ukraine Day" firstobservance="2023">День захисників і захисниць України</date>
	<date day="14" month="10" free="true" comment="Defenders of Ukraine Day" firstobservance="2015" lastobservance="2022">День захисників і захисниць України</date>
	<date day="25" month="12" free="true" comment="Christmas" firstobservance="2017">Різдво Христове</date>
	<date day="7" month="1" free="true" comment="Christmas (Gregorian Calendar)" lastobservance="2022">Різдво Христове</date>
</holidays>

=== heiglandreas/holidayChecker/share/NL.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="https://heigl.org/xml/xsd/holidays.xsd"
>
    <date day="1" month="1" free="true">Nieuwjaarsdag</date>
    <easter offset="-2" free="false">Goede Vrijdag</easter>
    <easter offset="1" free="true">Pasen</easter>
    <easter offset="0" free="false">Pasen</easter>
    <date day="27" month="4" free="true">Koningsdag</date>
    <date day="5" month="5" interval="5" firstobservance="1945" lastobservance="1990" free="true">Bevrijdingsdag</date>
    <date day="5" month="5" firstobservance="1990" free="true" restriction="paid free day only every 5 years">Bevrijdingsdag</date>
    <easter offset="40" free="true">Hemelvaartsdag</easter>
    <easter offset="49" free="true">Pinksteren</easter>
    <easter offset="50" free="true">Pinksteren</easter>
    <date day="5" month="12" free="false">Pakjesavond</date>
    <date day="25" month="12" free="true">Kerstmis</date>
    <date day="26" month="12" free="true">Kerstmis</date>
</holidays>

=== heiglandreas/holidayChecker/share/SR.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Culture_of_Suriname" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true">New Years Day</date>
	<date day="1" month="5" free="true">Labour Day</date>
	<date day="15" month="12" free="true" calendar="indian">Phagwah</date>
	<easter offset="-2" free="true">Good Friday</easter>
	<date day="5" month="6" free="true">Prawas Din</date>
	<date day="1" month="7" free="true">Keti koti</date>
	<!-- Javanese Arrival Day -->
	<date day="9" month="8" free="true">Indigenous People's Day</date>
	<!-- Day of the Maroons -->
	<!-- Chinese Arrival Date -->
	<!-- Independence Day -->
	<date day="27" month="7" free="true" calendar="indian">Diwali</date>
	<date day="10" month="12" free="true" calendar="islamic-civil">Eid-ul-Adha</date>
  <date day="31" month="10" free="false">Halloween</date>
	<date day="25" month="12" free="true">Christmas Day</date>
</holidays>

=== heiglandreas/holidayChecker/share/EC.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Ecuador" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true" comment="New Years Day">Año Nuevo</date>
	<date day="12" month="2" free="false" comment="Galapagos Day">dia de la Provincia de Galápagos</date>
	<easter offset="-48" free="true" comment="Carnival">Carnaval</easter>
	<easter offset="-47" free="true" comment="Carnival">Carnaval</easter>
	<easter offset="-2" free="true" comment="Good Friday">Viernes Santo</easter>
	<date day="1" month="5" free="true" comment="Labour Day">Día del Trabajo</date>
	<date day="24" month="5" free="true" comment="Battle of Pichincha">Batalla de Pichincha</date>
	<date day="10" month="8" free="true" comment="Declaration of Independence of Ecuador">Primer Grito de Independencia</date>
	<date day="9" month="10" free="true" comment="Independence of Guayaquil">Independencia de Guayaquil</date>
	<date day="2" month="11" free="true" comment="All Souls day">Día de Muertos</date>
	<date day="3" month="11" free="true" comment="Independence of Cuenca">Independencia de Cuenca</date>
	<date day="6" month="12" free="true" comment="Foundation of Quito">Fundación de Quito</date>
	<date day="25" month="12" free="true" comment="Christmas Day">Día de Navidad</date>
</holidays>

=== heiglandreas/holidayChecker/share/SI.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Slovenia" lastChecked="2026-07-26">Wikipedia</resource>
	</resources>
	<date day="1" month="1" free="true" comment="New years Day">novo leto</date>
	<date day="2" month="1" free="true"	comment="New Years Day" firstobservance="2017">novo leto</date>
	<date day="2" month="1" free="true"	comment="New Years Day" firstobservance="1955" lastobservance="2012">novo leto</date>
	<date day="8" month="2" free="true" comment="Prešeren Day">Prešernov dan</date>
	<easter offset="0" free="true" comment="Easter Sunday">velikonočna nedelja</easter>
	<easter offset="1" free="true" comment="Easter Monday">velikonočni ponedeljek</easter>
	<date day="27" month="4" free="true" comment="Day of Uprising Against Occupation">dan upora proti okupatorju</date>
	<date day="1" month="5" free="true" comment="May Day">praznik dela</date>
	<date day="2" month="5" free="true" comment="May Day">praznik dela</date>
	<easter offset="49" free="true" comment="Whit Sunday">binkošti</easter>
	<date day="25" month="6" free="true" comment="Statehood Day">dan državnosti</date>
	<date day="15" month="8" free="true" comment="Assumption Day" firstobservance="1992">Marijino vnebovzetje</date>
	<date day="31" month="10" free="true" comment="Reformation Day" firstobservance="1992">dan reformacije</date>
	<date day="1" month="11" free="true" comment="All Saints Day" lastobservance="1990">dan mrtvih</date>
	<date day="1" month="11" free="true" comment="All Saints Day" firstobservance="1991">dan spomina</date>
	<date day="25" month="12" free="true" comment="Christmas Day" lastobservance="1953">božič</date>
	<date day="25" month="12" free="true" comment="Christmas Day" firstobservance="1991">božič</date>
	<date day="26" month="12" free="true" comment="independence and unbity day">dan samostojnosti in enotnosti</date>
</holidays>

=== heiglandreas/holidayChecker/share/UY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
					xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
					xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Uruguay" lastChecked="2025-02-12"/>
	</resources>
	<date day="1" month="1" free="true" comment="New Years day">Año Nuevo</date>
	<date day="6" month="1" free="true" comment="Childrens Day">Día de los Niños</date>
	<easter offset="-48" free="true" comment="Carnival">Carnaval</easter>
	<easter offset="-47" free="true" comment="Carnival">Carnaval</easter>
	<easter offset="-46" free="true" comment="Carnival">Carnaval</easter>
	<easter offset="-7" free="true" comment="Tourism Week">Semana de Turismo</easter>
	<easter offset="-6" free="true" comment="Tourism Week">Semana de Turismo</easter>
	<easter offset="-5" free="true" comment="Tourism Week">Semana de Turismo</easter>
	<easter offset="-4" free="true" comment="Tourism Week">Semana de Turismo</easter>
	<easter offset="-3" free="true" comment="Tourism Week">Semana de Turismo</easter>
	<date day="19" month="4" free="true" comment="Landing of the 33 Patriots day">Desembarco de los 33 Orientales</date>
	<date day="1" month="5" free="true" comment="International Workers Day">Día de los Trabajadores</date>
	<date day="18" month="5" free="true" comment="Battle of Las Piedras">Batalla de las Piedras</date>
	<date day="18" month="6" free="true" comment="Birthday of Jose Gervasio Artigas">Natalicio de Artigas</date>
	<date day="18" month="7" free="true" comment="Constitution Day">Jura de la Constitución</date>
	<date day="25" month="8" free="true" comment="Independence Day">Declaratoria de la Independencia</date>
	<date day="12" month="10" free="true" comment="Da of the Armericans">Día de las Américas</date>
	<date day="2" month="11" free="true" comment="All Souls Day">Día de los Difuntos</date>
	<date day="25" month="12" free="true" comment="Family Day">Día de la Familia</date>
</holidays>

=== heiglandreas/holidayChecker/share/IS.xml
<?xml version="1.0" encoding="UTF-8" ?>
<holidays xmlns="https://heigl.org/holidays"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="holidays.xsd https://heigl.org/xml/xsd/holidays.xsd"
          xmlns:xi="http://www.w3.org/2001/XInclude"
>
	<resources>
		<resource href="https://en.wikipedia.org/wiki/Public_holidays_in_Iceland" lastChecked="2026-10-15">Wikipedia</resource>
		<resource href="https://is.wikipedia.org/wiki/L%C3%B6gbundnir_fr%C3%ADdagar_%C3%A1_%C3%8Dslandi" lastChecked="2026-10-15">Wikipedia (is)</resource>
		<resource href="https://www.visindavefur.is/svar.php?id=1692" lastChecked="2026-10-15">Vísindavefurinn</resource>
	</resources>
	<date day="1" month="1" free="true">Nýársdagur</date>
	<easter offset="-3" free="true">Skírdagur</easter>
	<easter offset="-2" free="true">Föstudagurinn langi</easter>
	<easter offset="0" free="true">Páskadagur</easter>
	<easter offset="1" free="true">Annar í páskum</easter>
	<relative day="18" month="4" relation="next thursday" free="true">Sumardagurinn fyrsti</relative>
	<date day="1" month="5" free="true">Verkalýðsdagurinn</date>
	<easter offset="39" free="true">Uppstigningardagur</easter>
	<easter offset="49" free="true">Hvítasunnudagur</easter>
	<easter offset="50" free="true">Annar í hvítasunnu</easter>
	<date day="17" month="6" free="true">Þjóðhátíðardagurinn</date>
	<relative day="1" month="8" relation="first monday of this month" free="true">Frídagur verslunarmanna</relative>
	<date day="24" month="12" free="true" restriction="from 13:00">Aðfangadagur</date>
	<date day="25" month="12" free="true">Jóladagur</date>
	<date day="26" month="12" free="true">Annar í jólum</date>
	<date day="31" month="12" free="true" restriction="from 13:00">Gamlársdagur</date>
</holidays>
